# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import 網路語料.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='語料表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('收錄時間', models.DateField(auto_now_add=True)),
                ('上尾修改時間', models.DateField(auto_now=True)),
                ('華語內容', models.TextField(blank=True)),
                ('華語來源', models.TextField(blank=True)),
                ('臺語內容', models.TextField()),
                ('臺語來源', models.TextField(default='{\n  "名": "",\n  "影片": "",\n  "網址": ""\n}', validators=[網路語料.models.愛有名])),
                ('文本內容', models.TextField()),
                ('音標內容', models.TextField()),
                ('文本音標來源', models.TextField(default='{\n  "名": "",\n  "影片": "",\n  "網址": ""\n}', validators=[網路語料.models.愛有名])),
                ('備註', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
