# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import 網路語料.models


class Migration(migrations.Migration):

    dependencies = [
        ('網路語料', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='語料表',
            name='文本音標來源',
            field=models.TextField(default='{\n  "名": "",\n  "影片": "",\n  "標題": "",\n  "種類": "",\n  "網址": "",\n  "著作年": "",\n  "著作所在地": "",\n  "語言腔口": ""\n}', validators=[網路語料.models.愛有名]),
        ),
        migrations.AlterField(
            model_name='語料表',
            name='臺語來源',
            field=models.TextField(default='{\n  "名": "",\n  "影片": "",\n  "標題": "",\n  "種類": "",\n  "網址": "",\n  "著作年": "",\n  "著作所在地": "",\n  "語言腔口": ""\n}', validators=[網路語料.models.愛有名]),
        ),
    ]
